// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    MyGrid: typeof import('./src/components/MyGrid.vue')['default']
    MyTable: typeof import('./src/components/MyTable.vue')['default']
    VxeButton: typeof import('vxe-table/es/button/index.js')['Button']
    VxeColumn: typeof import('vxe-table/es/column/index.js')['Column']
    VxeGrid: typeof import('vxe-table/es/grid/index.js')['Grid']
    VxeTable: typeof import('vxe-table/es/table/index.js')['Table']
  }
}
